# Generated by Django 2.1 on 2017-12-02 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeProductsWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='histroy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeProductsWebsite.History'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeProductsWebsite.Product'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeProductsWebsite.Review'),
        ),
        migrations.AlterField(
            model_name='product',
            name='histroy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeProductsWebsite.History'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeProductsWebsite.Review'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PrimeProductsWebsite.Review'),
        ),
    ]
