# Generated by Django 2.1 on 2017-12-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrimeProductsWebsite', '0002_auto_20171202_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
